### PR TITLE
Support RSpec 3

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by shepmaster** [comment]
@Gazler This branch has the modifications needed to test against RSpec 3. We can race to see who gets there first. :wink:

**Comment by Gazler** [comment]
@shepmaster The title should be RSpec 3 support btw.

**Comment by shepmaster** [comment]
@Gazler RSpec / Rails, what's the difference? :grin:

**Comment by Gazler** [comment]
@shepmaster I think the way the tests are structured are going to make it difficult to allow compatibility with both RSpec 2 and RSpec 3.

A lot of the tests are expectations on method calls such as:

```
@formatter.should_receive(:start).with(3)
@formatter.should_receive(:example_group_started).with(example_group)
@formatter.should_receive(:example_started).exactly(3).times
@formatter.should_receive(:example_passed).once
@formatter.should_receive(:example_failed).once
@formatter.should_receive(:example_pending).once
@formatter.should_receive(:start_dump).once
@formatter.should_receive(:dump_failure).once
@formatter.should_receive(:dump_summary).once
@formatter.should_receive(:dump_pending).once
@formatter.should_receive(:dump_failures).once
@formatter.should_receive(:close).once
```

Should we skip these tests in RSpec 3 and go on the acceptance tests? Or maintain a separate RSpec 2 branch and focus on RSpec 3 for the future?

**Comment by shepmaster** [comment]
This gem focuses largely on the integration of RSpec and CI::Reporter. As such, I think that the acceptance tests are most important to do.

What I would do is:
1/ Work on getting a single acceptance test to pass.
2/ Write _new_ classes that drive out that functionality (probably with an `RSpec3` in the name or so.
3/ As needed, write unit tests for those new classes. Try to have a light hand with the mocks and stubs, but sometimes this is unavoidable. These unit tests should probably focus on the strange edge cases and corners that are hardest to test via acceptance/integration tests.

Write your new classes in a similar structure and style as the existing ones, but don't worry about actually refactoring them to use the same code. Once it's written, we can take a look and clean them up accordingly.

Thanks for looking into this!

**Comment by Gazler** [comment]
@shepmaster I've ported the commit I made to the `ci_reporter` gem into this. I haven't fully tested it with my CI server yet (maybe tomorrow) but the acceptance tests are passing.

I have removed to RSpec 2 support for now - I figure we can get it working correctly and then change the code to support both.

The commit is https://github.com/Gazler/ci_reporter_rspec/commit/c05abe237dfc2558d9d37ed67eeffed03e4929f0

It's not ready for merging yet but I'd appreciate you taking a look at it.

**Comment by giedriusr** [comment]
Any news?

**Comment by shepmaster** [comment]
I hope to hack on this a bit tomorrow, around a wedding. :smile:

**Comment by giedriusr** [comment]
Cool. Waiting :+1:

**Comment by shepmaster** [comment]
Closed via #9

**Pull request closed without merging**
